name: larastore
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  dio: ^5.4.0
  equatable: ^2.0.5
  framework:
    path: /home/ervin/lib/flutter/framework
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  source_gen: ^1.5.0

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
