import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:larastore/dataset/meta.dart';

// required: associates our `*.dart` with the code generated by Freezed
part 'resource.freezed.dart';

part 'resource.g.dart';

/// Any model created on the backend.
@freezed
class Resource<T> with _$Resource {

  const factory Resource({Map<String, dynamic>? attributes, DatasetMeta? meta, String? error}) = _Resource;

  factory Resource.fail(String message) {
    return Resource(error: message);
  }

  // Create Dataset model from json node
  factory Resource.fromJson(Map<String, dynamic> node) =>
      _$ResourceFromJson(node);
}
